### PR TITLE
Update README.MD

### PR DESCRIPTION
**Pull request by reconsumeralization**
Typo Exsample fixed.

### CODE REVIEW

**Comment by reconsumeralization** [comment]
Im not sure if should be Example or Examples.
_9682ab30-2437-4def-bb38-8aa04d512618

**Comment by rliberoff** [comment]
Hi @reconsumeralization! 

Thank you for the fix!

Could you please update the version of the libraries. It is done here → https://github.com/Encamina/enmarcha/blob/4498a872f66746d7cc4bc28df9a2c62029a2022d/Directory.Build.props#L18C1-L21C19

**Review by rliberoff — CHANGES_REQUESTED** [review]
Thank you for the fix!

Could you please update the version of the libraries. It is done here → https://github.com/Encamina/enmarcha/blob/4498a872f66746d7cc4bc28df9a2c62029a2022d/Directory.Build.props#L18C1-L21C19

**Comment by rliberoff** [comment]
We regretfully have to close this outdated PR as the author has not addressed the comments. We value and welcome contributions from our community and hope for more active engagement in the future.

**Pull request closed without merging**
